import type { CatalogEntry } from './types';
import type {
  ProjectTypeId, LanguageId, FrontendId, BackendId,
  DatabasePrimaryId, CacheId, VectorId, SearchId, AnalyticsDbId,
  GraphId, TimeSeriesId, FrontendHostingId, BackendHostingId,
  DatabaseHostingId, CdnId, OrchestrationId, AuthProviderId,
  SocialProviderId, PaymentId, EmailId, SmsId, AnalyticsId,
  MonitoringId, StorageId, ManagedSearchId, FeatureFlagsId,
  CssFrameworkId, ComponentLibraryId, IconSetId, FontFamilyId,
  TranslationSourceId, UnitTestId, ComponentTestId, E2eTestId,
  ApiTestId, CiId, CdId, IacId, PackageManagerId, MonorepoId,
} from '@/types';

export type { CatalogEntry };

// =====================================================
//   PROJECT TYPES
// =====================================================
export const projectTypes: CatalogEntry<ProjectTypeId>[] = [
  { id: 'web-app', name: 'Web Application', nameAr: 'تطبيق ويب', category: 'Web', categoryAr: 'ويب', description: 'Interactive application accessed via browser.', descriptionAr: 'تطبيق تفاعلي يعمل عبر المتصفح.', pros: ['Cross-platform', 'SEO options'], bestFor: ['SaaS', 'Dashboards'], version: '—', difficulty: 'beginner', icon: 'Globe' },
  { id: 'mobile-app', name: 'Mobile Application', nameAr: 'تطبيق جوال', category: 'Mobile', categoryAr: 'جوال', description: 'Native or cross-platform app for iOS / Android.', descriptionAr: 'تطبيق أصلي أو متعدد المنصات.', pros: ['Push notifications', 'Native UX'], bestFor: ['Consumer apps'], version: '—', difficulty: 'intermediate', icon: 'Smartphone' },
  { id: 'desktop-app', name: 'Desktop Application', nameAr: 'تطبيق سطح مكتب', category: 'Desktop', categoryAr: 'سطح المكتب', description: 'App installed on Windows / macOS / Linux.', descriptionAr: 'تطبيق يثبت على ويندوز أو ماك.', pros: ['No browser limits'], bestFor: ['Dev tools'], version: '—', difficulty: 'intermediate', icon: 'Monitor' },
  { id: 'saas-platform', name: 'SaaS Platform', nameAr: 'منصة SaaS', category: 'Web', categoryAr: 'ويب', description: 'Subscription-based software.', descriptionAr: 'برنامج باشتراك.', pros: ['Recurring revenue'], bestFor: ['B2B tools'], version: '—', difficulty: 'advanced', icon: 'Cloud' },
  { id: 'ecommerce', name: 'E-commerce Store', nameAr: 'متجر إلكتروني', category: 'Commerce', categoryAr: 'تجارة', description: 'Online store for products.', descriptionAr: 'متجر على الإنترنت.', pros: ['Payment built-in'], bestFor: ['Retail'], version: '—', difficulty: 'intermediate', icon: 'ShoppingCart' },
  { id: 'marketplace', name: 'Two-sided Marketplace', nameAr: 'سوق ثنائي', category: 'Commerce', categoryAr: 'تجارة', description: 'Connects buyers and sellers.', descriptionAr: 'يربط بين البائعين والمشترين.', pros: ['Network effects'], bestFor: ['Services'], version: '—', difficulty: 'advanced', icon: 'Store' },
  { id: 'social-network', name: 'Social Network', nameAr: 'شبكة اجتماعية', category: 'Social', categoryAr: 'اجتماعي', description: 'User-generated content with feeds.', descriptionAr: 'محتوى ينشئه المستخدمون.', pros: ['Real-time feed'], bestFor: ['Communities'], version: '—', difficulty: 'advanced', icon: 'Users' },
  { id: 'blog-cms', name: 'Blog / CMS', nameAr: 'مدوّنة / CMS', category: 'Content', categoryAr: 'محتوى', description: 'Content publishing platform.', descriptionAr: 'منصة نشر محتوى.', pros: ['SEO-friendly'], bestFor: ['News'], version: '—', difficulty: 'beginner', icon: 'BookOpen' },
  { id: 'landing-page', name: 'Landing / Marketing Page', nameAr: 'صفحة هبوط', category: 'Web', categoryAr: 'ويب', description: 'Single conversion page.', descriptionAr: 'صفحة تحويل واحدة.', pros: ['Fast load'], bestFor: ['Product launches'], version: '—', difficulty: 'beginner', icon: 'Megaphone' },
  { id: 'api-backend', name: 'API / Backend Service', nameAr: 'API / خدمة خلفية', category: 'Backend', categoryAr: 'خلفية', description: 'REST / GraphQL / gRPC service.', descriptionAr: 'خدمة REST أو GraphQL.', pros: ['Reusable'], bestFor: ['Mobile backends'], version: '—', difficulty: 'intermediate', icon: 'Server' },
  { id: 'ai-ml-app', name: 'AI / ML Application', nameAr: 'تطبيق ذكاء اصطناعي', category: 'AI', categoryAr: 'ذكاء اصطناعي', description: 'App powered by LLMs / embeddings.', descriptionAr: 'تطبيق يعمل بنماذج لغات كبيرة.', pros: ['Vector search'], bestFor: ['Chatbots', 'RAG'], version: '—', difficulty: 'advanced', icon: 'Brain' },
  { id: 'data-dashboard', name: 'Data Dashboard', nameAr: 'لوحة بيانات', category: 'Analytics', categoryAr: 'تحليلات', description: 'Visualize metrics interactively.', descriptionAr: 'عرض المؤشرات تفاعليًا.', pros: ['Real-time charts'], bestFor: ['BI'], version: '—', difficulty: 'intermediate', icon: 'BarChart3' },
  { id: 'game', name: 'Game', nameAr: 'لعبة', category: 'Gaming', categoryAr: 'ألعاب', description: '2D / 3D game.', descriptionAr: 'لعبة ثنائية أو ثلاثية الأبعاد.', pros: ['Game engine'], bestFor: ['Browser games'], version: '—', difficulty: 'advanced', icon: 'Gamepad2' },
  { id: 'iot', name: 'IoT / Embedded', nameAr: 'إنترنت الأشياء', category: 'Hardware', categoryAr: 'عتاد', description: 'Connects to devices and sensors.', descriptionAr: 'يتصل بأجهزة وحساسات.', pros: ['MQTT'], bestFor: ['Smart home'], version: '—', difficulty: 'advanced', icon: 'Cpu' },
  { id: 'blockchain-web3', name: 'Blockchain / Web3', nameAr: 'بلوكتشين / ويب 3', category: 'Web3', categoryAr: 'ويب 3', description: 'Smart contracts, dApps.', descriptionAr: 'عقود ذكية وتطبيقات لامركزية.', pros: ['On-chain'], bestFor: ['DeFi'], version: '—', difficulty: 'advanced', icon: 'LinkIcon' },
  { id: 'chrome-extension', name: 'Browser Extension', nameAr: 'إضافة متصفح', category: 'Browser', categoryAr: 'متصفح', description: 'Chrome / Firefox add-on.', descriptionAr: 'إضافة متصفح.', pros: ['Wide distribution'], bestFor: ['Productivity'], version: '—', difficulty: 'intermediate', icon: 'Puzzle' },
  { id: 'cli-tool', name: 'CLI Tool', nameAr: 'أداة سطر أوامر', category: 'Dev Tools', categoryAr: 'أدوات', description: 'Command-line utility.', descriptionAr: 'أداة سطر أوامر.', pros: ['Scriptable'], bestFor: ['Dev tooling'], version: '—', difficulty: 'intermediate', icon: 'Terminal' },
  { id: 'library-sdk', name: 'Library / SDK', nameAr: 'مكتبة / SDK', category: 'Dev Tools', categoryAr: 'أدوات', description: 'Reusable package.', descriptionAr: 'حزمة قابلة لإعادة الاستخدام.', pros: ['Wide reach'], bestFor: ['Open source'], version: '—', difficulty: 'intermediate', icon: 'Package' },
];

// =====================================================
//   LANGUAGES
// =====================================================
export const languages: CatalogEntry<LanguageId>[] = [
  { id: 'typescript', name: 'TypeScript', nameAr: 'تايب سكربت', category: 'Language', categoryAr: 'لغة', description: 'JavaScript with static typing.', descriptionAr: 'جافاسكربت مع أنواع ثابتة.', pros: ['Type safety'], bestFor: ['Web apps'], version: '^5.6.0', difficulty: 'beginner', icon: 'Code2' },
  { id: 'javascript', name: 'JavaScript', nameAr: 'جافاسكربت', category: 'Language', categoryAr: 'لغة', description: 'The language of the web.', descriptionAr: 'لغة الويب.', pros: ['Universal'], bestFor: ['Quick prototypes'], version: 'ES2024', difficulty: 'beginner', icon: 'Code2' },
  { id: 'python', name: 'Python', nameAr: 'بايثون', category: 'Language', categoryAr: 'لغة', description: 'Readable, dominant in AI.', descriptionAr: 'مقروءة، مسيطرة على AI.', pros: ['AI ecosystem'], bestFor: ['AI/ML', 'APIs'], version: '^3.12.0', difficulty: 'beginner', icon: 'Code2' },
  { id: 'go', name: 'Go', nameAr: 'جو', category: 'Language', categoryAr: 'لغة', description: 'Fast, simple, concurrent.', descriptionAr: 'سريعة وبسيطة.', pros: ['Goroutines'], bestFor: ['Cloud services'], version: '^1.23.0', difficulty: 'beginner', icon: 'Code2' },
  { id: 'rust', name: 'Rust', nameAr: 'رست', category: 'Language', categoryAr: 'لغة', description: 'Memory-safe systems language.', descriptionAr: 'لغة أنظمة آمنة.', pros: ['No GC'], bestFor: ['Systems', 'Wasm'], version: '^1.81.0', difficulty: 'advanced', icon: 'Code2' },
  { id: 'java', name: 'Java', nameAr: 'جافا', category: 'Language', categoryAr: 'لغة', description: 'Enterprise-grade.', descriptionAr: 'لغة مؤسساتية.', pros: ['Mature'], bestFor: ['Enterprise'], version: '^21.0', difficulty: 'intermediate', icon: 'Code2' },
  { id: 'kotlin', name: 'Kotlin', nameAr: 'كوتلن', category: 'Language', categoryAr: 'لغة', description: 'Official Android language.', descriptionAr: 'اللغة الرسمية لأندرويد.', pros: ['Null safety'], bestFor: ['Android'], version: '^2.0.0', difficulty: 'intermediate', icon: 'Code2' },
  { id: 'swift', name: 'Swift', nameAr: 'سويفت', category: 'Language', categoryAr: 'لغة', description: "Apple's modern language.", descriptionAr: 'لغة آبل.', pros: ['Safe'], bestFor: ['iOS apps'], version: '^5.10.0', difficulty: 'intermediate', icon: 'Code2' },
  { id: 'ruby', name: 'Ruby', nameAr: 'روبي', category: 'Language', categoryAr: 'لغة', description: 'Productivity-focused.', descriptionAr: 'تركز على الإنتاجية.', pros: ['Rapid prototyping'], bestFor: ['Rails'], version: '^3.3.0', difficulty: 'beginner', icon: 'Code2' },
  { id: 'php', name: 'PHP', nameAr: 'بي إتش بي', category: 'Language', categoryAr: 'لغة', description: 'Server-side web language.', descriptionAr: 'لغة ويب من جهة الخادم.', pros: ['Easy hosting'], bestFor: ['WordPress'], version: '^8.3.0', difficulty: 'beginner', icon: 'Code2' },
  { id: 'elixir', name: 'Elixir', nameAr: 'إكسير', category: 'Language', categoryAr: 'لغة', description: 'Functional, real-time.', descriptionAr: 'وظيفية، فورية.', pros: ['Fault tolerance'], bestFor: ['Real-time'], version: '^1.17.0', difficulty: 'advanced', icon: 'Code2' },
  { id: 'scala', name: 'Scala', nameAr: 'سكالا', category: 'Language', categoryAr: 'لغة', description: 'Functional + OOP on JVM.', descriptionAr: 'وظيفية + كائنية.', pros: ['Big data'], bestFor: ['Spark'], version: '^3.4.0', difficulty: 'advanced', icon: 'Code2' },
  { id: 'dart', name: 'Dart', nameAr: 'دارت', category: 'Language', categoryAr: 'لغة', description: "Google's language for Flutter.", descriptionAr: 'لغة جوجل لـ Flutter.', pros: ['Single codebase'], bestFor: ['Flutter'], version: '^3.5.0', difficulty: 'intermediate', icon: 'Code2' },
  { id: 'cpp', name: 'C++', nameAr: 'سي بلس بلس', category: 'Language', categoryAr: 'لغة', description: 'High-performance systems.', descriptionAr: 'لغة عالية الأداء.', pros: ['Performance'], bestFor: ['Games'], version: 'C++20', difficulty: 'advanced', icon: 'Code2' },
  { id: 'csharp', name: 'C#', nameAr: 'سي شارب', category: 'Language', categoryAr: 'لغة', description: 'Microsoft language.', descriptionAr: 'لغة مايكروسوفت.', pros: ['Tooling'], bestFor: ['.NET'], version: '^12.0', difficulty: 'intermediate', icon: 'Code2' },
  { id: 'solidity', name: 'Solidity', nameAr: 'سوليديتي', category: 'Language', categoryAr: 'لغة', description: 'Ethereum smart contracts.', descriptionAr: 'عقود إيثريوم الذكية.', pros: ['Smart contracts'], bestFor: ['DeFi'], version: '^0.8.24', difficulty: 'advanced', icon: 'Code2' },
];

// =====================================================
//   FRONTENDS
// =====================================================
export const frontends: CatalogEntry<FrontendId>[] = [
  { id: 'react', name: 'React (Vite)', nameAr: 'رياكت (Vite)', category: 'SPA / CSR', categoryAr: 'صفحة واحدة', description: 'Library with Vite.', descriptionAr: 'مكتبة مع Vite.', pros: ['Largest ecosystem'], bestFor: ['SPAs'], version: 'react ^18.3.1 + vite ^5.4.0', difficulty: 'beginner', icon: 'Atom' },
  { id: 'nextjs', name: 'Next.js (App Router)', nameAr: 'نكست جي إس', category: 'Full-stack SSR', categoryAr: 'متعدد الطبقات', description: 'React framework with SSR, RSC.', descriptionAr: 'إطار رياكت مع SSR و RSC.', pros: ['SSR/ISR/RSC'], bestFor: ['SEO sites'], version: '^15.0.0', difficulty: 'intermediate', icon: 'Layers', tags: ['fullstack'] },
  { id: 'remix', name: 'Remix', nameAr: 'ريميكس', category: 'Full-stack SSR', categoryAr: 'متعدد الطبقات', description: 'Full-stack React.', descriptionAr: 'رياكت متكامل.', pros: ['Web standards'], bestFor: ['Data-heavy'], version: '^2.13.0', difficulty: 'intermediate', icon: 'Layers', tags: ['fullstack'] },
  { id: 'vue', name: 'Vue (Vite)', nameAr: 'فيو (Vite)', category: 'SPA / CSR', categoryAr: 'صفحة واحدة', description: 'Progressive framework.', descriptionAr: 'إطار تدريجي.', pros: ['Gentle learning'], bestFor: ['Mid-size apps'], version: 'vue ^3.5.0 + vite ^5.4.0', difficulty: 'beginner', icon: 'Triangle' },
  { id: 'nuxt', name: 'Nuxt', nameAr: 'نُكست', category: 'Full-stack SSR', categoryAr: 'متعدد الطبقات', description: 'Vue framework with SSR.', descriptionAr: 'إطار فيو مع SSR.', pros: ['Auto-imports'], bestFor: ['SaaS'], version: '^3.13.0', difficulty: 'intermediate', icon: 'Layers', tags: ['fullstack'] },
  { id: 'angular', name: 'Angular', nameAr: 'أنجولار', category: 'Full-stack SPA', categoryAr: 'مؤسساتي', description: 'Enterprise-grade.', descriptionAr: 'إطار مؤسساتي.', pros: ['Opinionated'], bestFor: ['Enterprise'], version: '^18.2.0', difficulty: 'advanced', icon: 'Triangle' },
  { id: 'svelte', name: 'Svelte', nameAr: 'سفيلت', category: 'SPA / CSR', categoryAr: 'صفحة واحدة', description: 'Compiled framework.', descriptionAr: 'إطار مترجم.', pros: ['Tiny bundles'], bestFor: ['Small apps'], version: '^5.0.0', difficulty: 'beginner', icon: 'Triangle' },
  { id: 'sveltekit', name: 'SvelteKit', nameAr: 'سفيلت كِت', category: 'Full-stack SSR', categoryAr: 'متعدد الطبقات', description: 'Full-stack Svelte.', descriptionAr: 'سفيلت متكامل.', pros: ['Fast'], bestFor: ['Web apps'], version: '^2.7.0', difficulty: 'intermediate', icon: 'Layers', tags: ['fullstack'] },
  { id: 'solid', name: 'SolidJS', nameAr: 'سوليد', category: 'SPA / CSR', categoryAr: 'صفحة واحدة', description: 'Fine-grained reactive.', descriptionAr: 'تفاعلي دقيق.', pros: ['Performance'], bestFor: ['High-perf UIs'], version: '^1.9.0', difficulty: 'intermediate', icon: 'Atom' },
  { id: 'astro', name: 'Astro', nameAr: 'أسترو', category: 'Islands / SSG', categoryAr: 'جزر ثابتة', description: 'Content-focused.', descriptionAr: 'يركّز على المحتوى.', pros: ['Zero JS default'], bestFor: ['Blogs', 'Docs'], version: '^4.16.0', difficulty: 'beginner', icon: 'Sparkles', tags: ['static'] },
  { id: 'qwik', name: 'Qwik', nameAr: 'كويك', category: 'Resumable SSR', categoryAr: 'استئناف', description: 'Resumable framework.', descriptionAr: 'إطار قابل للاستئناف.', pros: ['Instant TTI'], bestFor: ['E-commerce'], version: '^1.9.0', difficulty: 'advanced', icon: 'Zap' },
  { id: 'ember', name: 'Ember', nameAr: 'إمبير', category: 'Full-stack SPA', categoryAr: 'مؤسساتي', description: 'Productive, battle-tested.', descriptionAr: 'إطار منتج ومجرّب.', pros: ['Conventions'], bestFor: ['Long-lived'], version: '^5.12.0', difficulty: 'advanced', icon: 'Triangle' },
  { id: 'preact', name: 'Preact', nameAr: 'برياكت', category: 'SPA / CSR', categoryAr: 'صفحة واحدة', description: '3KB React alternative.', descriptionAr: 'بديل 3 كيلوبايت لرياكت.', pros: ['Tiny'], bestFor: ['Embedded widgets'], version: '^10.23.0', difficulty: 'beginner', icon: 'Atom' },
  { id: 'lit', name: 'Lit', nameAr: 'ليت', category: 'Web Components', categoryAr: 'مكونات الويب', description: 'Web Components library.', descriptionAr: 'مكتبة مكونات الويب.', pros: ['Standards-based'], bestFor: ['Design systems'], version: '^3.2.0', difficulty: 'intermediate', icon: 'Box' },
  { id: 'react-native', name: 'React Native (CLI)', nameAr: 'رياكت نيتف (CLI)', category: 'Mobile Native', categoryAr: 'جوال أصلي', description: 'Native iOS/Android with React.', descriptionAr: 'آيفون/أندرويد أصلي برياكت.', pros: ['Native'], bestFor: ['Mobile apps'], version: '^0.75.0', difficulty: 'intermediate', icon: 'Smartphone' },
  { id: 'expo', name: 'Expo', nameAr: 'إكسبو', category: 'Mobile Managed', categoryAr: 'جوال مُدار', description: 'Managed React Native.', descriptionAr: 'رياكت نيتف مُدار.', pros: ['EAS Build'], bestFor: ['Mobile'], version: '~51.0.0', difficulty: 'beginner', icon: 'Smartphone' },
  { id: 'flutter', name: 'Flutter', nameAr: 'فلاتر', category: 'Mobile Cross-platform', categoryAr: 'جوال متعدد', description: "Google's UI toolkit.", descriptionAr: 'مجموعة جوجل.', pros: ['Single codebase'], bestFor: ['Cross-platform'], version: '^3.24.0', difficulty: 'intermediate', icon: 'Layers' },
  { id: 'swiftui', name: 'SwiftUI', nameAr: 'سويفت يو آي', category: 'Apple Native', categoryAr: 'آبل أصلي', description: 'Apple declarative UI.', descriptionAr: 'واجهة آبل.', pros: ['Native'], bestFor: ['iOS apps'], version: 'iOS 17+', difficulty: 'intermediate', icon: 'Apple' },
  { id: 'jetpack-compose', name: 'Jetpack Compose', nameAr: 'جت باك كومبوز', category: 'Android Native', categoryAr: 'أندرويد أصلي', description: 'Modern Android UI.', descriptionAr: 'واجهة أندرويد حديثة.', pros: ['Declarative'], bestFor: ['Android'], version: '^1.7.0', difficulty: 'intermediate', icon: 'Smartphone' },
  { id: 'tauri', name: 'Tauri', nameAr: 'توري', category: 'Desktop Hybrid', categoryAr: 'سطح المكتب', description: 'Web frontend + Rust backend.', descriptionAr: 'ويب + رست.', pros: ['Tiny binaries'], bestFor: ['Desktop'], version: '^2.0.0', difficulty: 'intermediate', icon: 'Monitor' },
  { id: 'electron', name: 'Electron', nameAr: 'إلكترون', category: 'Desktop', categoryAr: 'سطح المكتب', description: 'Chromium + Node.', descriptionAr: 'كروم + نود.', pros: ['Mature'], bestFor: ['Desktop tools'], version: '^32.0.0', difficulty: 'intermediate', icon: 'Monitor' },
  { id: 'none', name: 'No Frontend', nameAr: 'بدون واجهة', category: 'None', categoryAr: 'بدون', description: 'No UI layer.', descriptionAr: 'بدون واجهة.', pros: ['Simpler'], bestFor: ['APIs', 'CLIs'], version: '—', difficulty: 'beginner', icon: 'Minus' },
];

// =====================================================
//   BACKENDS
// =====================================================
export const backends: CatalogEntry<BackendId>[] = [
  { id: 'express', name: 'Express.js', nameAr: 'إكسبريس', category: 'Node.js', categoryAr: 'نود جي إس', description: 'Minimal Node framework.', descriptionAr: 'إطار نود بسيط.', pros: ['Huge ecosystem'], bestFor: ['REST APIs'], version: '^4.21.0', difficulty: 'beginner', icon: 'Server' },
  { id: 'fastify', name: 'Fastify', nameAr: 'فاستفاي', category: 'Node.js', categoryAr: 'نود جي إس', description: 'Fast Node framework.', descriptionAr: 'إطار نود سريع.', pros: ['Very fast'], bestFor: ['High-throughput'], version: '^5.0.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'nestjs', name: 'NestJS', nameAr: 'نست جي إس', category: 'Node.js', categoryAr: 'نود جي إس', description: 'Angular-inspired.', descriptionAr: 'مستوحى من أنجولار.', pros: ['DI'], bestFor: ['Enterprise APIs'], version: '^10.4.0', difficulty: 'advanced', icon: 'Server' },
  { id: 'hono', name: 'Hono', nameAr: 'هونو', category: 'Edge Runtime', categoryAr: 'وقت تشغيل الحافة', description: 'Ultrafast edge framework.', descriptionAr: 'إطار ويب فائق السرعة.', pros: ['Edge-first'], bestFor: ['Cloudflare'], version: '^4.6.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'koa', name: 'Koa', nameAr: 'كوا', category: 'Node.js', categoryAr: 'نود جي إس', description: 'Expressive Node.', descriptionAr: 'إطار نود معبّر.', pros: ['Modern async'], bestFor: ['Custom APIs'], version: '^2.15.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'django', name: 'Django', nameAr: 'جانغو', category: 'Python', categoryAr: 'بايثون', description: 'Batteries-included.', descriptionAr: 'إطار بايثون شامل.', pros: ['Admin built-in'], bestFor: ['Content sites'], version: '^5.1.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'fastapi', name: 'FastAPI', nameAr: 'فاست أي بي آي', category: 'Python', categoryAr: 'بايثون', description: 'Modern async Python.', descriptionAr: 'بايثون حديث غير متزامن.', pros: ['Auto docs'], bestFor: ['AI/ML APIs'], version: '^0.115.0', difficulty: 'beginner', icon: 'Server' },
  { id: 'flask', name: 'Flask', nameAr: 'فلاسك', category: 'Python', categoryAr: 'بايثون', description: 'Lightweight Python.', descriptionAr: 'إطار بايثون خفيف.', pros: ['Simple'], bestFor: ['Microservices'], version: '^3.0.3', difficulty: 'beginner', icon: 'Server' },
  { id: 'spring-boot', name: 'Spring Boot', nameAr: 'سبرينج بوت', category: 'JVM', categoryAr: 'JVM', description: 'Enterprise Java.', descriptionAr: 'إطار جافا مؤسساتي.', pros: ['Enterprise'], bestFor: ['Banking'], version: '^3.3.0', difficulty: 'advanced', icon: 'Server' },
  { id: 'rails', name: 'Ruby on Rails', nameAr: 'روبي أون ريلز', category: 'Ruby', categoryAr: 'روبي', description: 'Convention over configuration.', descriptionAr: 'الاتفاقية فوق التهيئة.', pros: ['Rapid dev'], bestFor: ['SaaS'], version: '^7.2.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'laravel', name: 'Laravel', nameAr: 'لارافيل', category: 'PHP', categoryAr: 'بي إتش بي', description: 'PHP with elegant syntax.', descriptionAr: 'بي إتش بي بصياغة أنيقة.', pros: ['Eloquent ORM'], bestFor: ['Web apps'], version: '^11.6.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'symfony', name: 'Symfony', nameAr: 'سيمفوني', category: 'PHP', categoryAr: 'بي إتش بي', description: 'Enterprise PHP.', descriptionAr: 'إطار بي إتش بي مؤسساتي.', pros: ['Stable'], bestFor: ['Enterprise'], version: '^7.1.0', difficulty: 'advanced', icon: 'Server' },
  { id: 'gin', name: 'Gin (Go)', nameAr: 'جين (جو)', category: 'Go', categoryAr: 'جو', description: 'High-perf Go.', descriptionAr: 'إطار جو عالي الأداء.', pros: ['Fast'], bestFor: ['Microservices'], version: '^1.10.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'echo', name: 'Echo (Go)', nameAr: 'إيكو (جو)', category: 'Go', categoryAr: 'جو', description: 'High-perf Go.', descriptionAr: 'إطار جو عالي الأداء.', pros: ['Simple'], bestFor: ['APIs'], version: '^4.12.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'fiber', name: 'Fiber (Go)', nameAr: 'فايبر (جو)', category: 'Go', categoryAr: 'جو', description: 'Express-inspired Go.', descriptionAr: 'إطار جو مستوحى من Express.', pros: ['Express-like'], bestFor: ['APIs'], version: '^2.52.5', difficulty: 'beginner', icon: 'Server' },
  { id: 'actix', name: 'Actix Web (Rust)', nameAr: 'أكتِكس (رست)', category: 'Rust', categoryAr: 'رست', description: 'Fast Rust.', descriptionAr: 'إطار رست سريع.', pros: ['Extremely fast'], bestFor: ['High-perf'], version: '^4.9.0', difficulty: 'advanced', icon: 'Server' },
  { id: 'axum', name: 'Axum (Rust)', nameAr: 'أكسوم (رست)', category: 'Rust', categoryAr: 'رست', description: 'Tokio-powered Rust.', descriptionAr: 'إطار رست مع Tokio.', pros: ['Type-safe'], bestFor: ['Production Rust'], version: '^0.7.0', difficulty: 'advanced', icon: 'Server' },
  { id: 'aspnet', name: 'ASP.NET Core', nameAr: 'إيه إس بي دوت نت', category: '.NET', categoryAr: '.NET', description: 'Microsoft framework.', descriptionAr: 'إطار مايكروسوفت.', pros: ['Mature'], bestFor: ['Enterprise'], version: '^8.0.0', difficulty: 'intermediate', icon: 'Server' },
  { id: 'phoenix', name: 'Phoenix (Elixir)', nameAr: 'فينيكس (إكسير)', category: 'Elixir', categoryAr: 'إكسير', description: 'Real-time Elixir.', descriptionAr: 'إطار إكسير فوري.', pros: ['LiveView'], bestFor: ['Real-time'], version: '^1.7.0', difficulty: 'advanced', icon: 'Server' },
  { id: 'none', name: 'No Backend', nameAr: 'بدون backend', category: 'None', categoryAr: 'بدون', description: 'Frontend-only or serverless.', descriptionAr: 'واجهة فقط أو serverless.', pros: ['Simpler'], bestFor: ['Jamstack'], version: '—', difficulty: 'beginner', icon: 'Minus' },
];